[package]
name = "wrath"
version = "0.1.0"
authors = ["victov <victor.veldstra@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = {version="*", features=["attributes"] }
anyhow = { version = "*" }
podio = { version = "*" } 
dotenv = { version="*" }
sha-1 = { version = "*" }
rand = { version = "0.7" } 
num-bigint = { version = "0.3", features=["rand"] } 
num-traits = { version = "0.2.12" } 
wrath-auth-db = { path = "../databases/wrath-auth-db" }
tracing = {version="0.1"}
tracing-subscriber = {version = "0.2" }
